version: '3'
services: 
  jenkins-flask:
    build:
      dockerfile: Dockerfile.jenkins
      context: .
    ports:
      - "8080:8080"
  flask-app:
    build: .
    volumes: 
      - .:/app
    environment:
      APP_ENV: development
    ports:
      - "5000:5000"
  




    